### ISSUE TITLE
Propose: need more requirements

### ISSUE THREAD

**Issue by jongfeel** [kyu9341/TeamHash#21]
지금 한참 코딩하면서 기능 구현 하고 계신데
그 전에 조금 만들어 보면 좋을 걸 알려드리려고 이슈 남겨 봅니다.

### Use case

뜻은 용례로 이 프로젝트의 결과물을 가지고 사용자가 어떤 기능을 사용할 수 있고 어떤 결과를 얻을 수 있는지를 정리하는 문서입니다. 크게 use case scenario, use case diagram 같은 걸로 만들 수 있는데 한번 만들어 봤으면 좋겠습니다.

### Story board

프로젝트 전체 화면을 스크린샷 등으로 만들어 두고 설명을 하는 문서를 뜻합니다. 보통 영화에서도 쓰는 용어로 매 장면마다 연출해야 하는 인물이나 배경을 그리고 대사와 묘사 스크립팅이 첨부되는 형태입니다.
이 그림이 있어야 프로젝트 진행할 때 전체 분량에 따른 기능 구현 분할 및 집중을 할 수 있게 됩니다. 이것도 만들고 시작하면 좋겠습니다.

**Comment by kyu9341** [comment]
넵 조언 감사합니다!

**Comment by jongfeel** [comment]
이거 문서 작성 계획이 있나요?

**Comment by kyu9341** [comment]
네 작성 해보려고 합니다.
지금은 시간이 조금 부족해서 여유가 좀 생기면 해보려 합니다.

**Comment by jongfeel** [comment]
언제 할지 계획이 있으면 됩니다. 알겠습니다!
