### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by jongfeel** [kyu9341/TeamHash#36]
안녕하세요.
여러분들이 계속해서 문제를 해결하고 개발해 나가는 과정을 지켜보니
왠지 제가 도와드릴께 많이 없을 것 같다는 느낌이 드는군요
물론 좋은 의미에서 하는 얘기입니다.

특별히 문제 상황이 일어나도 서로 피드백 주면서 해결해 나가는 과정이 참 좋아보이고
commit, pull request, issue에 적은 내용을 봐도
열심히 하고 있다는 느낌이 많이 듭니다.

그래서 코로나 시국이 조금 풀릴 떄 쯤
리뷰 미팅 겸 해서 오프라인으로 보는 것도 좋을 것 같고
그 전이라도 온라인 미팅이 필요하면 요청해 주시면 좋을 것 같습니다.
한이음에서 온라인 미팅 최대 2회까지 인정해 준다고 했거든요.

아시겠지만 이렇게 해서 나온 지원금은 다 여러분들을 위해 쓰일겁니다.

**Comment by kyu9341** [comment]
안녕하세요!
그렇지 않아도 다음주 쯤에 오프라인 미팅이 가능하신지 여쭈어 보려고 했었는데 
먼저 물어봐주셨네요! 이번주에는 기사시험이 있어서 다음주에 혹시 오프라인 미팅이 가능하신가요?

**Comment by jongfeel** [comment]
평일은 수요일 빼고 가능할 거 같고
주말, 휴일도 가능합니다.

**Comment by kyu9341** [comment]
아하.. 넵 감사합니다.
오늘 회의 후에 날짜를 정해보겠습니다!

**Comment by kyu9341** [comment]
멘토님 다음주 화요일(9일) 저녁에 가능하실까요..?!

**Comment by jongfeel** [comment]
두 가지를 더 정해야 합니다.
- 장소
- 시간

장소는 한이음 토즈 회의실 목록을 보니 서울대입구는 있는 것 같습니다.
서울대입구가 좋을지 다른 곳이 좋을지 정하시면 좋고요.

시간은 평일이라 너무 늦으면 안되니까
오후 4시 이후에 볼 수 있으면 그때도 괜찮습니다.

**Comment by kyu9341** [comment]
승현이가 6시까지 신도림에서 국비교육을 들어서 혹시 7시쯤에 문래역 토즈는 어떠신가요..?

**Comment by jongfeel** [comment]
한이음 공지사항에 보면 문래역 토즈는 목록에 없었습니다.

■신촌본점

■강남2호점

■토즈타워점

■삼성점

■종로점

■홍대점

■분당서현점

■신반포점

■건대점

■교대점

■서울대점


그나마 가까운 곳이 홍대인 것 같아요. 시간은 오후 7시면 괜찮습니다.

**Comment by kyu9341** [comment]
아하..! 그러면 신촌 7시로 괜찮으실까요..!?

**Comment by jongfeel** [comment]
네 좋습니다. 회의실 잡아주시고 알려주세요.

**Comment by kyu9341** [comment]
![image](https://user-images.githubusercontent.com/49153756/83491189-572c9c80-a4ec-11ea-80ec-75b5b0a88ad8.png)
예약 완료했습니다!
