### ISSUE TITLE
Hanium gitlab penalty

### ISSUE THREAD

**Issue by jongfeel** [kyu9341/TeamHash#39]
어제 한이음 공지 올라온거 보니
gitlab을 쓰지 않으면 중간 평가에 페널티를 준다고 합니다.

github를 쓰고 gitlab으로 잠깐 옮긴다고 해도 commit 횟수나 기타 로그가 반영되지 않을거기 떄문에
gitlab으로 쓰는 건 어떨까 싶네요?
나중에 AWS 쓸 계획이 있는지 모르겠는데 중간평가에서 짤려서 지원금 못받으면 좀 아쉬우니까 gitlab이전을 고려해 보셨으면 좋겠습니다.

**Comment by wjrmffldrhrl** [comment]
지난번 gitlab을 사용할 때 불편한점이 많았던걸로 기억합니다.
한이음 뿐만 아니라 앞으로 포토폴리오로도 활용할 생각이기 때문에 github를 사용하고 싶습니다.

혹시 github를 계속 사용하면서 gitlab으로 복사를 종종 해주는 방식은 안될까요?

**Comment by jongfeel** [comment]
그럴려면 조금 부지런하셔야 하던가 누군가 전담해서 그 시간을 할애(라고 읽고 희생이라 씀) 해야 할거에요.

아니면 remote repository를 gitlab도 추가해서 하는 방법도 있습니다.
gitlab repository는 push용으로만 쓰는 거죠.

``` shell
$ git remote add gitlab-origin "https://lab.hanium.or.kr/20_hf025/main.git"
$ git push -u gitlab-origin master
```

이런식으로 추가해서 master branch 만이라도 commit log를 쌓아두면 크게 문제는 없을 것 같아요.

제가 예전에 프로젝트 할 때 백업용으로 이런식으로 했었습니다.

**Comment by wjrmffldrhrl** [comment]
remote repository를 추가하여 push용으로 쓰는 방법이 좋은 것 같습니다.
이번주 중으로 적용해보겠습니다.
 감사합니다.

**Comment by wjrmffldrhrl** [comment]
https://lab.hanium.or.kr/20_hf025/main

멘토님이 알려주신 방법으로 remote 추가하여 push 했습니다.

commit이 적용되는 것 같습니다.
