### ISSUE TITLE
Accessing Data JPA Application

### ISSUE THREAD

**Issue by wjrmffldrhrl** [kyu9341/TeamHash#6]
https://spring.io/guides/gs/accessing-data-jpa/  
위의 가이드를 보고 한번 진행해 보았습니다.

jo/spring_boot/workspace/accessing_data_jpa/README.md
제가 이해한 내용을 한번 정리해봤는데  

해당 가이드가 H2 데이터베이스를 이용하여 JPA로 데이터를 입출력하고 검색하는 과정인건가요?

**Comment by jongfeel** [comment]
네 그 튜토리얼인 듯 하네요. 한번 해보시고 이해해 보면 좋을 것 같습니다.
그리고 DB를 maria db를 쓴다고 했으니 DB만 바꿔주시면 될거에요
-> 어쩌면 코드도 조금 수정해야 할 수도 있습니다.

그리고 여러 팁을 알려드리면

### 질문 대상자 선택

![image](https://user-images.githubusercontent.com/17442457/79627959-9c348380-8177-11ea-941e-3da61d8762ce.png)

위 그림과 같이 Assignees를 선택하고 누구에게 할당할지를 고를 수 있습니다.

### 문서 링크하기

https://github.com/kyu9341/TeamHash/blob/jo/jo/spring_boot/workspace/accessing_data_jpa/README.md

이렇게 하면 링크가 걸립니다.

**Comment by wjrmffldrhrl** [comment]
감사합니다!
