### ISSUE TITLE
@PostMapping 오류

### ISSUE THREAD

**Issue by wjrmffldrhrl** [kyu9341/TeamHash#68]
# 발생한 문제
스케줄 삭제를 위해 자바스크립트를 활용하여 post 전송을 하는 함수를 구현해서 해당 URL로 스케줄의 id를 전송하였습니다.

그러나 403오류가 계속해서 발생합니다. 
![image](https://user-images.githubusercontent.com/49122299/85226773-3c2ab980-b414-11ea-8da5-c11186253b1d.png)

![image](https://user-images.githubusercontent.com/49122299/85226779-43ea5e00-b414-11ea-9128-609683cc5aac.png)
form 데이터를 확인하면 알 수 있듯이 데이터는 전송이 되고 있습니다.
## calendar.html
https://github.com/kyu9341/TeamHash/blob/a7a7020c5fb5fddc067e4cdc3296765b728231bf/src/main/resources/templates/project/calendar.html#L173-L194
이 함수를 삭제 버튼의 onclick 속성값으로 부여하였으며 매개변수로 넘어온 scheduleId를 받아 post로 전송하는 방식입니다.

## CalendarController.java
https://github.com/kyu9341/TeamHash/blob/a7a7020c5fb5fddc067e4cdc3296765b728231bf/src/main/java/kr/co/teamhash/project/calendar/CalendarController.java#L69-L112
해당 컨트롤러에서 URL Mapping이 이루어 집니다.

스케줄을 생성하는 과정도 삭제하는 과정과 동일해서 당연히 될 것이라고 생각하는데 안되는 이유를 찾지 못하겠습니다.

# 예상하는 문제 원인
1. 타임리프를 사용하지 않아서
2. 입력값을 넣어서 생성한 form 태그를 body에 붙여서
3. 어딘가에 존재하는 오타

이 외에는 짐작이 가지 않습니다.

**Comment by ytw9699** [comment]
scheduleId 가 컨트롤러에서는 sysout으로 찍힐거 같은데

혹시 뭐라고 에러가 뭐라고 나는지 로그도 올려주시면 좋을거 같네요~

**Comment by wjrmffldrhrl** [comment]
> scheduleId 가 컨트롤러에서는 sysout으로 찍힐거 같은데
> 
> 혹시 뭐라고 에러가 나는지 로그도 올려주시면 좋을거 같네요~

컨트롤러에서 mapping된 deleteSchedule메서드는  실행되질 않았습니다. 

mapping과정중에 문제가 있는 것 같아요

**Comment by ytw9699** [comment]
그럼 요청들어갔을때 개발자도구 콘솔창에서는,  url옆에 403만 나오나요?

**Comment by kyu9341** [comment]
확인 결과, csrf 토큰이 없어서 발생한 문제였고 setRequestHeader로 csrf 토큰을 추가하여 요청해 문제를 해결했습니다.

**Comment by ytw9699** [comment]
네 저도 그부분 보고 있었네요 post방식의 경우 토큰값이 필요한데. settings.html보니 csrf값을 주석 처리해두셨던데 그 부분을 수정하신게 맞나요?

**Comment by kyu9341** [comment]
아뇨, 그 부분이 csrf토큰 값을 가져오는 부분이고 calendar.html 에서 발생했던 문제였기 때문에 csrf를 받아오는 부분을 추가하여 해결했습니다.  타임리프에서 csrf토큰을 가져오는 방법입니다.
```javascript
var csrfToken = /*[[${_csrf.token}]]*/ null;
var csrfHeader = /*[[${_csrf.headerName}]]*/ null;
```

**Comment by ytw9699** [comment]
네 결국 calendar.html안에 토큰값을 가져오셔서 post로 전송하셨다는거 같네요~?

**Comment by kyu9341** [comment]
네네 맞습니다!!

**Comment by ytw9699** [comment]
"타임리프 템플릿으로 form 생성시 자동으로 csrf 토큰 기능을 지원" 신기하네요
저도 하나 공부하고 갑니다^^ 감사합니다.

**Comment by jongfeel** [comment]
주말, 휴일에 올라온거라 메일 확인만 했는데
제가 추측했던 건 403이니까 인증 과정을 확인해 보면 되지 않을까...만 생각했었습니다.
저도 좋은거 하나 알아가네요

**Comment by wjrmffldrhrl** [comment]
다들 확인해주셔서 감사합니다!
