### ISSUE TITLE
ui 수정중에 있어요 한번 보시고 의견내주세영

### ISSUE THREAD

**Issue by cats0713** [kyu9341/TeamHash#77]
![image](https://user-images.githubusercontent.com/49222407/86555541-9fc3f380-bf8b-11ea-956b-ad9c8ccb6f91.png)
전
![image](https://user-images.githubusercontent.com/49222407/86555560-aeaaa600-bf8b-11ea-9fcf-7361705ed49d.png)
후

어떤게 나은지 아님 다른 디자인도 추천해주시거나 의견 내주세용

**Comment by wjrmffldrhrl** [comment]
계속 보니까 #이 커도 괜찬은 것 같습니다.

**Comment by cats0713** [comment]
네 의견 감사합니다!
