### ISSUE TITLE
What's next plan?

### ISSUE THREAD

**Issue by jongfeel** [kyu9341/TeamHash#83]
마지막으로 작업한 commit 이후 두 달 정도가 지났는데요

이후 추가 작업 계획이 있으신가요?

아니면 이 상태로 한이음 결과를 제출하실 건가요?

**Comment by cats0713** [comment]
외관을 조금 더 손 봐야할거같아서 작업은 조금 해보려고 합니다.

**Comment by jongfeel** [comment]
알겠습니다.

그 정도 작업 진행 후에 마무리를 할 예정이신가요?
