### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by wjrmffldrhrl** [kyu9341/TeamHash#85]
궁금한 내용이 생기고 빠르게 피드백을 받고싶어서 난생 처음으로 아는 영어 모르는 영어 다 써서 스택오버플로우에 [질문](https://stackoverflow.com/questions/64493166/how-can-i-generate-pattern-array-from-string-array-in-java)을 올려봤습니다.  

아래는 제가 올린 질문 전문입니다.  

---
# How can i generate Pattern array from String array in java
I want generate Pattern array from String array.

So i write code like this
```
public class LawDataPersonNameFinder implements PersonNameFinder{
    String[] backConditionRegxArray = {"\\s외\\s\\d\\s인"};
    Pattern[] backConditionPatterns;

    public LawDataPersonNameFinder() {
        backConditionPatterns = new Pattern[backConditionRegxArray.length];
        int index = 0;
        for (String str : backConditionRegxArray) {
            backConditionPatterns[index++] = Pattern.compile(str);
        }
    }

    @Override
    public Area[] findPersonNAme(String text) {
        return new Area[0];
    }
}

```
`backConditionRegxArray` can be added at any time

But i want to use Stream... how can i do that?  

---  

한 10분정도 지나고 답글이 달리고 좋아라 할 때  
![image](https://user-images.githubusercontent.com/49122299/97025873-9b036980-1593-11eb-9b2b-2ff2fb66f403.png)
질문글에 대해서 지적이 들어오더니  

![image](https://user-images.githubusercontent.com/49122299/97025617-48c24880-1593-11eb-8ae3-63854b931b05.png)
제 질문글은 비추천을 받고   

![image](https://user-images.githubusercontent.com/49122299/97025818-89ba5d00-1593-11eb-8b60-1c1d957d69c3.png)
심지어는 어떤 사람이 와서 문법 교정을 해주고 갔습니다.  

![image](https://user-images.githubusercontent.com/49122299/97025948-b5d5de00-1593-11eb-8dff-67577a132905.png)  
이후에는 질문이 닫혔습니다.  

스택오버플로우에서 글을 보기만 했지 직접 써보는건 처음이라 조심스럽게 접근하긴 했는데 어렵네요... 원래 이런곳인가요?

**Comment by jongfeel** [comment]
얘기해 드릴게 두 가지가 있네요.

1. 저도 저런식으로 두 번이나 비추를 받았습니다.

잘 몰라서 그런것도 아닌데 비추를 받으면 그냥 짤립니다. 그리고 저 답변은 그래도 친절한 겁니다. 그냥 question guideline은 쳐다보고 온거 맞냐? 검색은 해봤냐? 로 비아냥 거리는 댓글이 거의 정상입니다.

2. 다른 stackoverflow 질문을 잘 보고 비슷하게 따라하면 됩니다.

답변 달아준 사람도 적었지만 의도가 뭐냐? 이게 중요합니다. 그래서 내가 뭘 하고 싶은데 뭘 해봤고 뭐가 안되고 이걸 아주 자세하게 적어야 합니다. 저도 두번이나 비추 받고 마상 입긴 했는데, 결국 질문 올리는거 보다 질문을 찾는게 더 비용적으로 절감이고 더 쉽다는 결론에 이르게 됩니다.

그리고 stackoverflow가 유명하긴 하지만 꼭 여기서 답을 찾아야 하는 건 아니니 너무 상처받지 마세요. 저도 stackoverflow에는 질문 안올립니다.

**Comment by wjrmffldrhrl** [comment]
좋은 경험이 되었습니다.  
쉬운곳은 아니네요 ㅎㅎㅎ; 나중에 정말정말 모르겠을때 다시 한번 도전해봐야겠어요

**Comment by ytw9699** [comment]
저는 올려보진 못했는데 질문이 닫히는건 처음알았네요..ㄷㄷ 새로운거 알아갑니다~!
